### ISSUE TITLE
Type commad on respond

### ISSUE THREAD

**Issue by zhaohansprt** [bajrangCoder/acode-plugin-acodex#10]
it will no respond unless you switch out the acode app and then back,  after first one or more commands excuted and respond successfully

my environment:   
android phone :onoplus 7TP 
system:              android 11
terminal:            termux (updated just)

**Comment by bajrangCoder** [comment]
I can't face this, can you share a screen record (video) of this problem, so i can fix it

**Comment by zhaohansprt** [comment]
https://user-images.githubusercontent.com/23518809/236651579-3ebbd292-c6e5-4443-860f-71087313be3e.mp4

the bug start at 19 seconds

**Comment by zhaohansprt** [comment]
> I can't face this, can you share a screen record (video) of this problem, so i can fix it 

hi there is the record video ,snice the bug appears randomly ,sometimes soon sometimes it take a few of try

**Comment by bajrangCoder** [comment]
Oo, I haven't seen this, Thanks reporting!

I will fix it soon.
But please try the latest `v1.1.0` and please provide configuration, is it still exists (bug) or its fixed?

**Comment by bajrangCoder** [comment]
ok i will fix it as soon as possible...

**Comment by zhaohansprt** [comment]
> ok i will fix it as soon as possible...

nice

**Comment by 14725** [comment]
Hope I don't making disturbances.

I met the same problem, and it's not too hard to reproduce by pushing a lot of things in  terminal in one go.

e.g.
```

https://github.com/bajrangCoder/acode-plugin-acodex/assets/32530438/d1ffb8ac-e304-470b-b724-29757018e6b3


```

**Comment by bajrangCoder** [comment]
> Hope I don't making disturbances.
> 
> I met the same problem, and it's not too hard to reproduce by pushing a lot of things in terminal in one go.
> 
> e.g.
> 
>  Screenrecording_20230603_160006.mp4 
> It might be a performance issue. Maybe limiting the maxinum lines in a session may help?

I am working on it to fix, yes i am using this limiting column approach

**Comment by bajrangCoder** [comment]
> > I can't face this, can you share a screen record (video) of this problem, so i can fix it
> 
> hi there is the record video ,snice the bug appears randomly ,sometimes soon sometimes It takes a little more trying

I have test AcodeX on Android 9, 10, 13(some how ) but I haven't tested on Android 12, 11. As i know it maybe due security issues.
Can you share a new recording if you still face.(Please also including recording of termux too)
