### ISSUE TITLE
How to uninstall this server?

### ISSUE THREAD

**Issue by alfiaff** [bajrangCoder/acode-plugin-acodex#11]
Hey bro, I have questions,
How do I uninstall this server? because I want to 
Re-install this server and I have more problem 
![Screenshot_2023-05-12-18-58-47](https://github.com/bajrangCoder/acode-plugin-acodex/assets/113286738/dc08ee33-c3f2-495d-b89d-b7e575236601)
I really I don't know  why.
Sorry my English is so bad 😞
I hope you understand with my sentences

**Comment by bajrangCoder** [comment]
Simply run `rm -rf .acodeX-server` and Restart **Termux**
