### ISSUE TITLE
The font size is too big...

### ISSUE THREAD

**Issue by wesleyzago120** [bajrangCoder/acode-plugin-acodex#12]
I think the font size should be reduced to be more in-line to Termux. It feels exaggerated big even on a 6.8" screen phone. But i really like the plugin makes my life so much easier.
![Screenshot_20230523_103415_Acode](https://github.com/bajrangCoder/acode-plugin-acodex/assets/119027777/a7139112-afdd-4a12-a6d9-5d0881300637)

**Comment by bajrangCoder** [comment]
You can change font size.
From here:
Settings>Plugins>Acode Plugin
Then on AcodeX plugin page you will get a setting icon on top right corner, just click it and it will open up this plugin setting page , where you can change font size, font family, cursor style , themes and much more..

Glad to hear that my plugin makes things easier for you ♥️♥️

**Comment by wesleyzago120** [comment]
Oh thank you so much, now the plugin is perfect. 😃
