### ISSUE TITLE
install fail showing no file acodeX-server.zip found  what do i do

### ISSUE THREAD

**Issue by DivineMaster** [bajrangCoder/acode-plugin-acodex#13]

**Comment by bajrangCoder** [comment]
Try again and share screenshot of the problem

**Comment by DivineMaster** [comment]
The link in the repository is not working it is doing nothing.
so i did some extra effort because of that i was able to download it.
as i have already downloaded it i cannot provide screenshot.

Thanks, for answering



Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
