### ISSUE TITLE
Followed all steps, acodeX-server command not found

### ISSUE THREAD

**Issue by KP-Boateng** [bajrangCoder/acode-plugin-acodex#15]
![Screenshot_20230612-040912_Termux](https://github.com/bajrangCoder/acode-plugin-acodex/assets/72589907/e7ea9e71-3edb-4a69-bf96-bef503624298)

I'm using Android 11

**Comment by bajrangCoder** [comment]
First run `rm -rf .acodeX-server` then run `bash installServer.sh`

**Comment by KP-Boateng** [comment]
It worked. Thanks. Another problem tho. I'm trying to create a project using vite and i need the arrow keys up or down, unfortunately the arrow keys provided doesn't move selector up or down. Also where's the ctrl button, could see only the command button

**Comment by bajrangCoder** [comment]
Check Acode latest version, there is Ctrl key available in quick tools and I will fix arrow key issue in next update.
