### ISSUE TITLE
Floating Button

### ISSUE THREAD

**Issue by 0110vi** [bajrangCoder/acode-plugin-acodex#17]
Thank you for the update the new look is very clean and the folder button is super handy.  However please allow the new floating button to be a toggle option.  Maybe selectable from the plugin settings. It takes up too much space, I much preferred the old bookmark tab that poked up from the bottom left corner.

Not really an issue, just my suggestion. thanks

**Comment by bajrangCoder** [comment]
If i will add a setting to increase or decrease the size of button then it would be good?

**Comment by 0110vi** [comment]
Ya that would help.  It also gets hidden behind the keyboard every time it
pops up from the bottom, its more trouble for me than its worth!  well
thats not true, I still love the thing. I miss the old button though, I
thought it did the job perfectly

**Comment by bajrangCoder** [comment]
Ok then I will add a setting to change from new floating button or old btn

**Comment by 0110vi** [comment]
awesome! I appreciate the updates

**Comment by bajrangCoder** [comment]
Checkout latest `v1.1.5`, I have made it small and fixed at bottom left but don't worry it's also dragable (if you want)

**Comment by 0110vi** [comment]
It looks much better small, but the original issue remains.  Actually it
might be worse now.

As before, it slides behind the keyboard after moving it. It should move
upward with the keyboard even after relocating it.

Now this is the bad part,  after moving the buton, if you then exit the
plugin completely via the ... command pallette,  you lose the plugin
completely.  here are steps to reproduce.:

1. install plugin
2. open window via the "open terminal" command from command pallette
3. minimize window with _ button
4.  relocate the draggable button to any new position
5.  exit the plugin via "close terminal" from the command palette.
6. relaunch the plugin via "open terminal".
---> The terminal window and button do not reappear.

**Comment by bajrangCoder** [comment]
Thank you for reporting this crucial bug , I will provide Patch as soon as possible

**Comment by bajrangCoder** [comment]
Please check the latest version! It's fixed.
If you are enjoying the AcodeX plugin then make sure to leave a honest review on acode review section of this plugin 😊 for the new users
