### ISSUE TITLE
Made a Tasker Profile for Acode + AcodeX

### ISSUE THREAD

**Issue by GR3YH4TT3R93** [bajrangCoder/acode-plugin-acodex#20]
First off, I'd like to say I really like your work!

As a small token of my appreciation for the help your plugin has had in my workflow, I'd like to share a Tasker profile I set up to automatically start the AcodeX Server in Termux when you open Acode and close Termux completely when exiting Acode without requiring root or ADB.

Here's the link to the profile if you're interested and would like to add it and the directions to your README for everyone else to use: https://taskernet.com/shares/?user=AS35m8kU0ccWxDrK4Dlu2JWTOZT3CNq6GM5mrvtzDskXz8aeQWDUHQ1bkH8fmulu6vGZ0vZI&id=Profile%3AAcodeX

**Comment by LsxMm** [comment]
> 首先，我想说我真的很喜欢你的工作！
> 
> 为了表达我对您的插件在我的工作流程中提供的帮助的感谢，我想分享一个我设置的 Tasker 配置文件，以便在您打开 Acode 时自动启动 Termux 中的 AcodeX 服务器，并在退出 Acode 时完全关闭 Termux，而无需需要 root 或 ADB。
> 
> 如果您有兴趣并希望将其添加到您的自述文件中，以供其他人使用，请点击以下链接：[https://taskernet.com/shares/ ?user=AS35m8kU0ccWxDrK4Dlu2JWTOZT3CNq6GM5mrvtzDskXz8aeQWDUHQ1bkH8fmulu6vGZ0vZI&id=Profile%3AAcodeX](https://taskernet.com/shares/?user=AS35m8kU0ccWxDrK4Dlu2JWTOZT3CNq6GM5mrvtzDskXz8aeQWDUHQ1bkH8fmulu6vGZ0vZI&id=Profile%3AAcodeX)

I used your method without any response

**Comment by GR3YH4TT3R93** [comment]
Unfortunately, There is an issue with acodeX-server interpreter that prevents it from working at the moment.

Currently when attempting to run the script via termux-tasker it tries to run using /usr/bin/env instead of the correct shebang of #!/data/data/com.termux/files/usr/bin/env

It should be a very quick and easy change of the shebang for [this file](https://github.com/bajrangCoder/acodex-server/blob/main/bin/acodex-server) @bajrangCoder

**Comment by bajrangCoder** [comment]
> Unfortunately, There is an issue with acodeX-server interpreter that prevents it from working at the moment.
> 
> Currently when attempting to run the script via termux-tasker it tries to run using `#!/usr/bin/env` instead of the correct shebang of `#!/data/data/com.termux/files/usr/bin/env`
> 
> It should be a very quick and easy change of the shebang for [this file](https://github.com/bajrangCoder/acodex-server/blob/main/bin/acodex-server) @bajrangCoder

Contributions are welcomed 🤝

**Comment by LsxMm** [comment]
> 不幸的是，acodeX-server 解释器存在一个问题，目前无法工作。
> 
> 目前，当尝试通过 termux-tasker 运行脚本时，它会尝试使用 /usr/bin/env 而不是 #!/data/data/com.termux/files/usr/bin/env 的正确 shebang 运行
> 
> [此文件](https://github.com/bajrangCoder/acodex-server/blob/main/bin/acodex-server)的 shebang 的更改应该非常快速且简单[](https://github.com/bajrangCoder/acodex-server/blob/main/bin/acodex-server) @bajrangCoder

I tried your method, but there was no response

https://github.com/bajrangCoder/acode-plugin-acodex/assets/86006776/b1098621-8c5f-4cb8-90f3-d27946b20236

**Comment by LsxMm** [comment]
> > 不幸的是，acodeX-server 解释器存在一个问题，目前无法工作。
> > 目前，当尝试通过 termux-tasker 运行脚本时，它会尝试使用 /usr/bin/env 而不是 #!/data/data/com.termux/files/usr/bin/env 的正确 shebang 运行
> > [此文件](https://github.com/bajrangCoder/acodex-server/blob/main/bin/acodex-server)的 shebang 的更改应该非常快速且简单 @bajrangCoder
> 
> 我尝试了你的方法，但没有任何反应
> 
>  mmexport1713956138578.mp4

![Screenshot_20240424_185838](https://github.com/bajrangCoder/acode-plugin-acodex/assets/86006776/67962801-17ea-44d3-a203-e0f0efa0d6db)
This is the log

**Comment by GR3YH4TT3R93** [comment]
> > Unfortunately, There is an issue with acodeX-server interpreter that prevents it from working at the moment.
> > Currently when attempting to run the script via termux-tasker it tries to run using `#!/usr/bin/env` instead of the correct shebang of `#!/data/data/com.termux/files/usr/bin/env`
> > It should be a very quick and easy change of the shebang for [this file](https://github.com/bajrangCoder/acodex-server/blob/main/bin/acodex-server) @bajrangCoder
> 
> Contributions are welcomed 🤝

How do I build the project locally for testing? I'd like to make sure it's working before making any commits and creating a pull request.

**Comment by GR3YH4TT3R93** [comment]
@LsxMm running `npm update -g` should fix your issue

**Comment by LsxMm** [comment]
> @LsxMm现在跑步`npm update -g`应该可以解决你的问题

My problem is not with startup, but with the use of Task without any response

**Comment by LsxMm** [comment]
> > @LsxMm现在跑步`npm update -g`应该可以解决你的问题
> 
> 我的问题不是启动，而是使用任务没有任何响应

I want to implement it as a Task when I open Acode Auto start service

**Comment by LsxMm** [comment]
> > > @LsxMm现在跑步`npm update -g`应该可以解决你的问题
> > 
> > 
> > 我的问题不是启动，而是使用任务没有任何响应
> 
> 将 acodeX-server.txt 转换为 acodeXserver.sh 那么文件的内容应该是
> 
> ```
> #!/data/data/com.termux/files/usr/bin/env zsh
> 
> axs
> ```


https://github.com/bajrangCoder/acode-plugin-acodex/assets/86006776/1f700f7f-5cb9-4e14-b3a2-10b10f370a7e

The maximum file size is only 10MB, which is very troublesome and cannot be recorded for too long

**Comment by GR3YH4TT3R93** [comment]
Here's it working for me as expected

https://www.dropbox.com/scl/fi/6hi58c6vilpj4jdo7zswt/VID_20240424054822.mp4?rlkey=iiau9a1o8fb44o39u9rxl12an&raw=1

**Comment by GR3YH4TT3R93** [comment]
> > > > @LsxMm现在跑步`npm update -g`应该可以解决你的问题
> > > 
> > > 
> > > 我的问题不是启动，而是使用任务没有任何响应
> > 
> > 
> > 将 acodeX-server.txt 转换为 acodeXserver.sh 那么文件的内容应该是
> > ```
> > #!/data/data/com.termux/files/usr/bin/env zsh
> > 
> > axs
> > ```
> 
> mmexport1713961963609.mp4
> 
> The maximum file size is only 10MB, which is very troublesome and cannot be recorded for too long

[Here's](https://www.dropbox.com/scl/fi/6hi58c6vilpj4jdo7zswt/VID_20240424054822.mp4?rlkey=iiau9a1o8fb44o39u9rxl12an&raw=1) it working for me as expected (You will need to change close-acodeX-server.txt contents to pkill node for it to kill the server upon closing Acode)

https://www.dropbox.com/scl/fi/6hi58c6vilpj4jdo7zswt/VID_20240424054822.mp4?rlkey=iiau9a1o8fb44o39u9rxl12an&raw=1

**Comment by LsxMm** [comment]
> > > > > @LsxMm现在跑步`npm update -g`应该可以解决你的问题
> > > > 
> > > > 
> > > > 我的问题不是启动，但使用任务没有任何响应
> > > 
> > > 
> > > 将 acodeX-server.txt 转换为 acodeXserver.sh 那么文件的内容应该是
> > > ```
> > > #!/data/data/com.termux/files/usr/bin/env zsh
> > > 
> > > axs
> > > ```
> > 
> > 
> > mmexport1713961963609.mp4
> > 文件大小最大只有10MB，很麻烦，而且不能录太久
> 
> [这是](https://www.dropbox.com/scl/fi/6hi58c6vilpj4jdo7zswt/VID_20240424054822.mp4?rlkey=iiau9a1o8fb44o39u9rxl12an&raw=1)它按预期为我工作（您需要更改 close-acodeX-server.txt 内容，以便`pkill node`它在关闭 Acode 时杀死服务器）

I can't even run it. I plan to give up

**Comment by GR3YH4TT3R93** [comment]
What is the issue?

If you don't enable the check box at the beginning of the video, nothing will happen visually.

That is why I checked the box in the beginning of the video but it causes Acode to go into a loop of opening termux and running the server. To prevent that, the box should be unchecked like shown in the video but it gives no indication that it's working. The only way to tell if it's working is if you open Acode, hit `Ctrl+k`, and the console pops up as expected.

**Comment by GR3YH4TT3R93** [comment]
> > > > > > @LsxMm现在跑步`npm update -g`应该可以解决你的问题
> > > > > 
> > > > > 
> > > > > 我的问题不是启动，但使用任务没有任何响应
> > > > 
> > > > 
> > > > 将 acodeX-server.txt 转换为 acodeXserver.sh 那么文件的内容应该是
> > > > ```
> > > > #!/data/data/com.termux/files/usr/bin/env zsh
> > > > 
> > > > axs
> > > > ```
> > > 
> > > 
> > > mmexport1713961963609.mp4
> > > 文件大小最大只有10MB，很麻烦，而且不能录太久
> > 
> > 
> > [这是](https://www.dropbox.com/scl/fi/6hi58c6vilpj4jdo7zswt/VID_20240424054822.mp4?rlkey=iiau9a1o8fb44o39u9rxl12an&raw=1)它按预期为我工作（您需要更改 close-acodeX-server.txt 内容，以便`pkill node`它在关闭 Acode 时杀死服务器）
> 
> I can't even run it. I plan to give up

What is the issue?

If you don't enable the check box like I did at the beginning of the video, nothing will happen visually.

That is why I checked the box in the beginning of the video but it causes it to go into a loop of opening termux and running the server when trying to open or switch to Acode. To prevent that, the box should be unchecked like shown in the video but it gives no indication that it's working.

The only way to tell if it's working is if you open Acode, hit Ctrl+k, and the console pops up as expected.

**Comment by LsxMm** [comment]
> > > > > > > @LsxMm现在跑步`npm update -g`应该可以解决你的问题
> > > > > > 
> > > > > > 
> > > > > > 我的问题不是启动，但使用任务没有任何响应
> > > > > 
> > > > > 
> > > > > 将 acodeX-server.txt 转换为 acodeXserver.sh 那么文件的内容应该是
> > > > > ```
> > > > > #!/data/data/com.termux/files/usr/bin/env zsh
> > > > > 
> > > > > axs
> > > > > ```
> > > > 
> > > > 
> > > > mmexport1713961963609.mp4
> > > > 文件大小最大只有10MB，很麻烦，而且不能录太久
> > > 
> > > 
> > > [这是](https://www.dropbox.com/scl/fi/6hi58c6vilpj4jdo7zswt/VID_20240424054822.mp4?rlkey=iiau9a1o8fb44o39u9rxl12an&raw=1)您按我工作的预期（需要更改 close-acodeX-server.txt 内容，以便`pkill node`它在关闭 Acode 时杀死服务器）
> > 
> > 
> > 我什至无法运行它。我打算放弃
> 
> 有什么问题吗？
> 
> 如果您没有像我在视频开头那样启用该复选框，则视觉上不会发生任何事情。
> 
> 这就是为什么我选中了视频开头的复选框，但它导致它在尝试打开或切换到 Acode 时进入打开 termux 并运行服务器的循环。为了防止这种情况，应取消选中该框，如视频中所示，但它没有表明它正在工作。
> 
> 判断它是否正常工作的唯一方法是打开 Acode，按 Ctrl+k，然后控制台会按预期弹出。


https://github.com/bajrangCoder/acode-plugin-acodex/assets/86006776/349af083-793a-4e54-8da7-d6d8d7de40d3

I have tried many methods, but none of them have responded

**Comment by GR3YH4TT3R93** [comment]
Did you hit the check mark in the main menu of tasker after making changes?

**Comment by LsxMm** [comment]
> Did you hit the check mark in the main menu of tasker after making changes?

I have tried it all, and I have also tried opening the app. It works normally, but there is no response on termux

**Comment by GR3YH4TT3R93** [comment]
Hmm... If you updated the server, it should be working now. When you made your first comment, there was an issue with the server preventing it from working. If you've ran `npm update -g` and have everything properly set up (acodeX-server.txt with `axs` and close-acodeX-server.txt with `pkill node` in ~/.termux/tasker) it should be working.
