### ISSUE TITLE
FEATURE REQUEST: Nerd Font Icon compatibility

### ISSUE THREAD

**Issue by GR3YH4TT3R93** [bajrangCoder/acode-plugin-acodex#22]
Currently, nerd font icons show up as boxes instead of the correct icon

How to reproduce:
1. make acodeX-server open a zsh shell instead of bash (.acodex-server/index.js, change "bash" to "zsh")
2. install oh-my-zsh
3. install Powerlevel10k theme
4. restart termux or reload shell
5. enable icons in p10k configuration
6. open terminal in Acode
7. icons will show as boxes

Sorry if this isn't the right place to report this, I'm just not sure if this is an AcodeX limitation or an Acode limitation but I figured I'd start with the plugin and report to Acode if it's not a plugin specific issue

**Comment by bajrangCoder** [comment]
I thought I can fix it by using xterm-font-ligeature addon, Let me try then only I can say it's plugin specific issue or app.
Btw thanks for suggestion ❤️

**Comment by bajrangCoder** [comment]
I have found a way to achieve it: by loading the required font by the theme. 
Soon, I will provide an option to do so.

**Comment by bajrangCoder** [comment]
This issue is patched in `v2.1.0`.
Check it out!

**Comment by GR3YH4TT3R93** [comment]
I don't get what's going on.

If I set the font, it works for that session but as soon as I close the app and reopen it, it's back to the previous font.

How to reproduce:

In termux:
cd (ensure in home directory)
mkdir GitHub
cd GitHub
mkdir Backup
cd Backup
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip
(Extract zip)
touch FiraCode.css
(replicate FiraCode.css found here: https://github.com/GR3YH4TT3R93/dotfiles/tree/main/GitHub/Backup/FiraCode.css)

In Acode:
Open terminal (ensure icons aren't working)
Close terminal
Open settings >> plugins >> AcodeX >> settings
Select Custom Font Style Sheet >> FiraCode.css
Clear Font Family (or don't)
Add "FiraCode" (no quotes, can place anywhere in the list if you didn't clear Font Family)
Open terminal (ensure icons are working)
Close app
Open app
Open terminal
No icons again, settings reverted to original

Where am I going wrong?

**Comment by GR3YH4TT3R93** [comment]
I don't get what's going on.

If I set the font, it works for that session but as soon as I close the app and reopen it, it's back to the previous font.

How to reproduce:

In termux:
cd (ensure in home directory)
mkdir GitHub
cd GitHub
mkdir Backup
cd Backup
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip
(Extract zip)
touch FiraCode.css
(replicate FiraCode.css found here: https://github.com/GR3YH4TT3R93/dotfiles/tree/main/GitHub/Backup/FiraCode.css)

In Acode:
Open terminal (ensure icons aren't working)
Close terminal
Open settings >> plugins >> AcodeX >> settings
Select Custom Font Style Sheet >> FiraCode.css
Clear Font Family
Add 'Fira Code' (with single quotes)
Open terminal (ensure icons are working)
Close app
Open app
Open terminal
No icons again, settings reverted to original

Where am I going wrong?

**Comment by GR3YH4TT3R93** [comment]
And I'm sorry if this isn't the place and you'd like me to open another issue, but logo-ls icons still don't work

**Comment by bajrangCoder** [comment]
Sorry

**Comment by GR3YH4TT3R93** [comment]
Much better! It's now remembering font across restarts but logo-ls still doesn't work for some reason. The icons work correctly in termux so sadly,I don't think it's a font specific issue.

Thanks for the fast turnaround on the fix though! Awesome work as usual!

**Comment by bajrangCoder** [comment]
> Much better! It's now remembering font across restarts but logo-ls still doesn't work for some reason. The icons work correctly in termux so sadly,I don't think it's a font specific issue.
> 
> Thanks for the fast turnaround on the fix though! Awesome work as usual!

Don't be sad!
It can be fix. I have seen your custom font css file (https://github.com/GR3YH4TT3R93/dotfiles/blob/main/GitHub/Backup/FiraCode.css) there are some issues:

1) you have given same name to all font, give it like that : FiraCode Regular etc.. according it's corresponding font file and
2) in AcodeX font family Settings provide all font names without Single inverted comma as well as also separate your all font with Comma so AcodeX will load all.
For eg: FiraCode Light, FiraCode Regular , and so on..

**Comment by bajrangCoder** [comment]
It will definitely work because I also tried it
Here is my custom font css file:
https://dpaste.org/DMQn7

And in my AcodeX > Settings>Font Family, I have written: `MesloLGS NF Regular, MesloLGS NF Bold, MesloLGS NF Italic, MesloLGS NF Bold Italic`

> Note: Also makes sure to load icon font file , provided my theme.

**Comment by GR3YH4TT3R93** [comment]
Icons in the command prompt were/are working even with my bad config but logo-ls icons still don't work even with the config you provided.

How to reproduce:
  apt install logo-ls
  logo-ls
  logo-ls -lah .

![See attached photo for details](https://github.com/bajrangCoder/acode-plugin-acodex/assets/76727386/d8b36565-c7ef-4bb2-b52e-250b5102485e)

**Comment by bajrangCoder** [comment]
Ok , I haven't tested! Let me test it.

**Comment by GR3YH4TT3R93** [comment]
I know for a fact I'm using nerd fonts... Source: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip found here: https://www.nerdfonts.com/font-downloads

**Comment by GR3YH4TT3R93** [comment]
Working correctly in termux with same fonts
![Uploading Screenshot_2023-08-30-09-43-17-60_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by bajrangCoder** [comment]
is your font file and custom css file is in same folder?
and have given names of loaded custom font file in acodex font family settings?

**Comment by bajrangCoder** [comment]
Are you on Android 13?

**Comment by tharindu899** [comment]
you have css file give me bro

**Comment by bajrangCoder** [comment]
> you have css file give me bro

Which css file?

**Comment by tharindu899** [comment]
FiraCode css file

**Comment by tharindu899** [comment]
> Ok , I haven't tested! Let me test it.
> 
> Edit: It's working for me (because i have loaded nerd font) See 👇 ![Screenshot_20230830-133602_1](https://private-user-images.githubusercontent.com/71929976/264274289-f9bd532b-a803-4948-98af-122b59e6dc01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTY0OTAsIm5iZiI6MTcxMTUxNjE5MCwicGF0aCI6Ii83MTkyOTk3Ni8yNjQyNzQyODktZjliZDUzMmItYTgwMy00OTQ4LTk4YWYtMTIyYjU5ZTZkYzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA1MDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlN2RkNDliZDJjZDNmZjBkNzM2NmY5ODkzZWJiZGRkNDE0NzUxMDZlMmQwZmY4MDk4ZmRjMzFlMmU5YjRhMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7RwwqmbyQ_II3f3gWuTh-rX_p7JjDJyk1qD2YmeVEi4)
> 
> It's not working on your device because you have loaded simple fira code font which doesn't contains icon , and you will need icon here. So you will need to load any font from here (you can download fira code nerd icon ) https://github.com/ryanoasis/nerd-fonts#patched-fonts

like this

**Comment by bajrangCoder** [comment]
> FiraCode css file my zsh icon not show

FiraCode nerd font file is built in inside AcodeX , just select them from Acodex settings> Font Family

**Comment by bajrangCoder** [comment]
> > Ok , I haven't tested! Let me test it.
> > Edit: It's working for me (because i have loaded nerd font) See 👇 ![Screenshot_20230830-133602_1](https://private-user-images.githubusercontent.com/71929976/264274289-f9bd532b-a803-4948-98af-122b59e6dc01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTY0OTAsIm5iZiI6MTcxMTUxNjE5MCwicGF0aCI6Ii83MTkyOTk3Ni8yNjQyNzQyODktZjliZDUzMmItYTgwMy00OTQ4LTk4YWYtMTIyYjU5ZTZkYzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA1MDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlN2RkNDliZDJjZDNmZjBkNzM2NmY5ODkzZWJiZGRkNDE0NzUxMDZlMmQwZmY4MDk4ZmRjMzFlMmU5YjRhMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7RwwqmbyQ_II3f3gWuTh-rX_p7JjDJyk1qD2YmeVEi4)
> > It's not working on your device because you have loaded simple fira code font which doesn't contains icon , and you will need icon here. So you will need to load any font from here (you can download fira code nerd icon ) https://github.com/ryanoasis/nerd-fonts#patched-fonts
> 
> like this

Check out this: https://github.com/bajrangCoder/acode-plugin-acodex?tab=readme-ov-file#custom-fonts

**Comment by tharindu899** [comment]
![Screenshot_20240328_094722_com foxdebug acodefree](https://github.com/bajrangCoder/acode-plugin-acodex/assets/116081100/cc2919b2-d83a-49c0-8095-455c7e0396d5)
icon not woeking bro

**Comment by bajrangCoder** [comment]
I guess that's because FiraCode nerd font doesn't contains that icons, try `Meslo` font from Acodex settings (As meslo have a lots of nerd icon, hopefully that will work)
