### ISSUE TITLE
Expose acodex plugin

### ISSUE THREAD

**Issue by 7HR4IZ3** [bajrangCoder/acode-plugin-acodex#25]
Add the plugin instance to acode.require
I'm trying to develop a plugin to run file that uses termux

So i want to be able to do something like:

```javascript
terminal = acode.require('acodex').getTerminal();

if (terminal) {
  terminal.execute("python " + filepath )
}
```

**Comment by bajrangCoder** [comment]
Done ,
Check <kbd>v2.0.0</kbd>

**Comment by 7HR4IZ3** [comment]
It works but can you make it so we can do something like:

```javascript
result = await acodex.execute('ls');
acodex.openInTerminal('ls');

// or
let terminal = acodex.Terminal({ port: 9000 });
terminal.maximise();
terminal.execute('ls')
```

Because right now when I run the code it works but I don't see the output untill I open the terminal and I also want to see the prompt in the terminal

And also add a way to check if a terminal is currently opened.

**Comment by bajrangCoder** [comment]
Ok, wait for next update

**Comment by 7HR4IZ3** [comment]
Hi

I've uploaded the plugin
https://acode.foxdebug.com/plugin/acode.coderunner.plugin

Currently working on the stop button
Was hoping I could do something like.

```javascript
run() {
 setStopBtn();
  execute(command).then(setRunBtn())
}

stop() {
  execute("^C")
}
```

**Comment by bajrangCoder** [comment]
Yes you can stop using the same `execute` method.
Ref: https://github.com/bajrangCoder/acode-plugin-acodex/blob/b832a70dd785390c734035ace8ccf00d876ab6af/src/main.js#L615


For eg:
```js
execute("\x03"); // Ctrl+c , it will intrupt the running process
```

**Comment by bajrangCoder** [comment]
I thought these methods are enough.
Methods:
`execute(command)`
`isMinimized()`
`isTerminalOpened()`
`maximiseTerminal()`
`openTerminal(termContainerHeight, port)`
`closeTerminal()`
`convertAcodeUriToTermReadable(path)`

**Comment by 7HR4IZ3** [comment]
It is but I was wondering if it would be possible to make like tabs for the terminals

So something like:
`new acodex.Terminal()`
will create a new tab

So you only need to expose getActiveTerminal function and Terminal class

Or should I try to create it then submit a pull request??

**Comment by bajrangCoder** [comment]
I will think about it later . because there is no any implementation of multiple sessions or tabs in AcodeX .
 If you want you can. But first wait for v2.1.0 because I have changed a lot of things .

> Version 2.1.0 will be out either today or tomorrow.

**Comment by 7HR4IZ3** [comment]
Okayy..
