### ISSUE TITLE
"acodeX-server: command not found" in termux while "`acodeX-server` installed successfully."

### ISSUE THREAD

**Issue by Nimiaoye** [bajrangCoder/acode-plugin-acodex#30]
When I was trying to connect Acode with Termux using AcodeX, the resultare as follows:
![image](https://github.com/bajrangCoder/acode-plugin-acodex/assets/125271054/b3bbfdff-7b6d-481c-b3ea-03682cecccc2)
And I wonder how can I solve this problem. Thank you!

**Comment by bajrangCoder** [comment]
First tell me from where you have downloaded termux?
It seems you have downloaded it from `Play Store` but Termux is deprecated from `Play Store` instead download it from `f-droid` or from `termux GitHub repo`

**Comment by Nimiaoye** [comment]
I downloaded the Termux from github https://github.com/termux/termux-app/releases
![image](https://github.com/bajrangCoder/acode-plugin-acodex/assets/125271054/ac01c8c9-0a82-4424-9731-4f337f9cf76b)
I downloaded  this .apk and installed the termux

**Comment by bajrangCoder** [comment]
> I downloaded the Termux from github https://github.com/termux/termux-app/releases ![image](https://user-images.githubusercontent.com/125271054/270565387-ac01c8c9-0a82-4424-9731-4f337f9cf76b.png) I downloaded this .apk and installed the termux

Try universal version because many packages breakes on this version, I don't know why

**Comment by Nimiaoye** [comment]
Eh…I am a beginner in Github,so I think that universal version means Termux downloaded from f-droid? I can try it.
My equipment is Samsung Tab s8 with ARM v9 architecture.

**Comment by bajrangCoder** [comment]
Hm, According to your cpu architecture arm64-v8a is not for your device, So try universal ome because that's for every device

**Comment by Nimiaoye** [comment]
OK，I’ll try it.
Thank you!
