### ISSUE TITLE
Installing acodex in termux doesn't works

### ISSUE THREAD

**Issue by Aplha101** [bajrangCoder/acode-plugin-acodex#33]
I copy pasted the link to install acodex in termux but nothing happened
Am i missing something?

**Comment by bajrangCoder** [comment]
After pasting the installation link , nothing happens?
Are you using deprecated version of termux?

**Comment by Aplha101** [comment]
> After pasting the installation link , nothing happens?
> Are you using deprecated version of termux?

![Screenshot_2023-09-28-14-51-31-401_com.android.chrome.jpg](https://github.com/bajrangCoder/acode-plugin-acodex/assets/76000535/32093768-c2e8-429b-8dfa-d1487c76c31d)

This is the version I installed , the second one

**Comment by Aplha101** [comment]
> After pasting the installation link , nothing happens?
> Are you using deprecated version of termux?

@bajrangCoder is there any fix? I tried reinstalling termux from Fdroid still the same issue

**Comment by bajrangCoder** [comment]
> > After pasting the installation link , nothing happens?
> > Are you using deprecated version of termux?
> 
> @bajrangCoder is there any fix? I tried reinstalling termux from Fdroid still the same issue

Just install it manually by following the given methods:

- in termux first update your packages using:
```bash
pkg update && pkg upgrade
```
- now install required dependencies:
```bash
pkg install nodejs python
```
- now install `acodex-server` package using:
```bash
npm i -g acodex-server
```
- after installation, you can use `acodeX-server` command to start the server in termux
