### ISSUE TITLE
Don't ask for port

### ISSUE THREAD

**Issue by mzivic7** [bajrangCoder/acode-plugin-acodex#36]
Currently, port in acodex-server can't be externally changed from default 8767, so there is no need to ask for it every time acodex plugin terminal is launched (correct me if I am wrong).

So, port should be configurable in settings, in order to lower number of taps needed to connect to server.

**Comment by bajrangCoder** [comment]
You can change port while starting the server.

But I like your idea ,In next update there will a setting for it and it will be not asked at time of opening.

Thanks for suggesting 😃

**Comment by mzivic7** [comment]
Oh, you are using environment variable PORT. 
I had to search code to find that. 
You should point that out somewhere, or better: add command argument `-p <port>`.

**Comment by bajrangCoder** [comment]
Ok
