### ISSUE TITLE
Issue on instalation

### ISSUE THREAD

**Issue by haikal059** [bajrangCoder/acode-plugin-acodex#4]
![Screenshot_2023-02-27-11-15-10-538_com termux](https://user-images.githubusercontent.com/43695662/221465528-8b38d018-32ea-4daa-bcef-150dca345eff.jpg)

I got erro in instalation

**Comment by bajrangCoder** [comment]
I thought you have installed already.
By the way first run `rm -rf .acodeX-server`
And then run installation command

**Comment by haikal059** [comment]
> I thought you have installed already. By the way first run `rm -rf .acodeX-server` And then run installation command

Oke thanks is work
