### ISSUE TITLE
Unable to enter port number in Acode

### ISSUE THREAD

**Issue by kanodecat** [bajrangCoder/acode-plugin-acodex#42]
After installing the add-on and installing the server via the curl command. I ran acodeX-server through termux and then went to acode and used the command shortcut "ctrl+k" and get the error "Start the acodeX Server in termux first!" I would show images but I can't figure out how to upload them through this issue page.

I'm running grapheneos on version 2023120800 on a pixel 6. Plugin version is v3.0.1. Here's what I got when running uname
`uname -a
Linux localhost 5.10.200-android13-4-gb559d5ab185a #1 SMP PREEMPT Thu Dec 7 05:20:47 UTC 2023 aarch64 Android`

Also both apps, acode and termux have been granted all permissions to access the network, sensors, etc.

**Comment by bajrangCoder** [comment]
I have already tested on previous grapheneos and it worked at that time.

Is there any message or anything when you run the `acodeX-server` ?

You can enter port number from **AcodeX setting page** (from Acode App > Settings > Plugin> AcodeX plugin page > and ⚙️ icon on top)

**Comment by kanodecat** [comment]
Sorry for the late response. I didn't realize you could edit the port from there. Here are some of the screenshots I got 
![Screenshot_20231210-140256](https://github.com/bajrangCoder/acode-plugin-acodex/assets/56785252/a7ca13be-385d-45e5-b3cd-2cd2649c47a6)
![Screenshot_20231210-140231](https://github.com/bajrangCoder/acode-plugin-acodex/assets/56785252/3cfac81d-0823-4475-be8e-d7d3be9c43d0)
![Screenshot_20231210-140211](https://github.com/bajrangCoder/acode-plugin-acodex/assets/56785252/a274705b-20cb-49bc-9ae5-d99f6ba2da6a)

What's really interesting is that when I go to the AcodeX setting page to change the port. The extension still doesn't recognize that the server is open on said port.
![Screenshot_20231211-131331](https://github.com/bajrangCoder/acode-plugin-acodex/assets/56785252/7d4bfe0a-ac37-4c0a-b47e-ded6303e9655)

I hope this helps!

**Comment by bajrangCoder** [comment]
It's unexpected!!!

Try by reinstalling the AcodeX plugin in Acode(not the server)

**Comment by kanodecat** [comment]
Sorry about the long wait. I'm not sure what caused the issue initially, but reinstalling Termux solved it. Reinstalling the Acode app, the plugin, and the server didn't fix the problem so it ended up being a Termux problem I don't understand. However, once I reinstalled Termux, I successfully got the node server to work, and it connected with the plugin.
