### ISSUE TITLE
Font issues kerning

### ISSUE THREAD

**Issue by falasyam** [bajrangCoder/acode-plugin-acodex#45]
It's look weird when i have font spacing/kerning(idk). Look at my screenshot. I've changed the font, changed the font size but it's still like that.

My device is Xiaomi Redmi Note 11, Android 13, and Plugin Version v3.0.1

![IMG_20231221_085344](https://github.com/bajrangCoder/acode-plugin-acodex/assets/29745861/f1850be0-107f-4be4-af56-9c71f9e7bcea)

How to fix it? Thanks.

**Comment by bajrangCoder** [comment]
It seems fonts isn't loaded, which font you are using ?

**Comment by falasyam** [comment]
Ah, my bad, Previously I had tried various existing fonts but it didn't close the terminal. I tried to select the font then close the terminal and then open it again and it fixed. No more weird again.

**Comment by bajrangCoder** [comment]
Ok but there is a bug that it doesn't refresh the the terminal after changing the font
