### ISSUE TITLE
The spacing in the terminal's text is too big 

### ISSUE THREAD

**Issue by fathidevs** [bajrangCoder/acode-plugin-acodex#47]
The text is spaced out greatly, I changed the font family but issue didn't resolve. I hope you can fix it because it's taking unnecessary width and considering the phone's screen dimensions, it's kinda annoying.

Android 13, AcodeX version 3.0.1

**Comment by bajrangCoder** [comment]
Try by changing font family from settings, and also restart once to see effect,

**Comment by fathidevs** [comment]
The problem was in the Acode app itself and by reinstalling the Acode app the problem was solved.

**Comment by bajrangCoder** [comment]
Ok 👌
