### ISSUE TITLE
Acodex Terminal stops working after updating to v3.1.0

### ISSUE THREAD

**Issue by BizzyEL** [bajrangCoder/acode-plugin-acodex#49]
After updating to v3.1.0,
- The settings column disappears
- Ctrl-k no longer opens/launches the terminal
- acodeX-Server no longer starts the terminal server as expected
Thus, nothing works after the update.
I've tried uninstalling and reinstalling everything including python & nodejs (on termux), yet nothing works.
I even tried the curl approach rather than using npm i -g, same issue still.
Is this normal or did I miss something or do something wrong?

**Comment by bajrangCoder** [comment]
Have you updated both Plugin and server ?
And is there any error at the time of updating plugin?
Tell me your Android version?

> Btw sorry for Inconvenience 😔

**Comment by bajrangCoder** [comment]
Try v3.1.1

**Comment by BizzyEL** [comment]
Working perfectly now (i.e. with v3.1.1).
Thanks

**Comment by bajrangCoder** [comment]
Your welcome 🤗

> Btw share your feedback on new update for other users
