### ISSUE TITLE
gyp ERR! stack Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by ahmedrabbiff** [bajrangCoder/acode-plugin-acodex#5]
gyp ERR! stack Error: `make` failed with exit code: 2

**Comment by bajrangCoder** [comment]
Share a screenshot.
Or check your internet connection

**Comment by ahmedrabbiff** [comment]
![Uploading Screenshot_20230319-100625_Termux.jpg…]()

**Comment by ahmedrabbiff** [comment]
Full page screenshot 
https://ibb.co/NjNg0gn

**Comment by bajrangCoder** [comment]
Link isn't working...

**Comment by ahmedrabbiff** [comment]
https://i.ibb.co/LtgDTDh/Screenshot-20230319-100625-Termux.jpg

**Comment by bajrangCoder** [comment]
Yeah got it.
There 3 user have already reported this issue and they all uses same termux designing script (mayTermux/myTermux) , so i think this is the problem with it. You can wait for new version, i am making a standalone for it so it can run any termux , specially on these.

Thanks for reporting ❤️❤️

**Comment by ahmedrabbiff** [comment]
I'm waiting 
Thanks ❤️

**Comment by ahmedrabbiff** [comment]
Issue fixed
