### ISSUE TITLE
can't run code

### ISSUE THREAD

**Issue by Gibbz** [bajrangCoder/acode-plugin-acodex#54]
Describe about your problem

Trying to run code. But it can't find the file in the home directory.
I assume the termux server should copy the file across before running. But it doesn't seem to be doing that.

Provide few details about your device(like Android version) , Plugin version.

**Comment by bajrangCoder** [comment]
I thought that's because you haven't saved the file

**Comment by Sickdused** [comment]
Mine says permission denied even though I gave permission to the acode app., so I can't run my selected code in acodex terminal. I'am using a Cherry Aqua Tab Ultra running Android 11.
![Screenshot_20240219-082839](https://github.com/bajrangCoder/acode-plugin-acodex/assets/92903009/15d908df-01bc-4746-bfe2-2cfe7a3dc0a9)
![Screenshot_20240219-082816](https://github.com/bajrangCoder/acode-plugin-acodex/assets/92903009/55f28160-575a-4fb2-9440-bd1402646aed)
![Screenshot_20240219-082809](https://github.com/bajrangCoder/acode-plugin-acodex/assets/92903009/ae6894f4-3590-443b-9968-19ec5bedb781)
![Screenshot_20240219-082950](https://github.com/bajrangCoder/acode-plugin-acodex/assets/92903009/4392db74-df47-4979-b11c-15a9d294948a)

**Comment by bajrangCoder** [comment]
Then termux don't have permission, so you run given command to give permission in termux:

```
termux-setup-storage
```
