### ISSUE TITLE
acodeX-server: command not found

### ISSUE THREAD

**Issue by 8376459** [bajrangCoder/acode-plugin-acodex#55]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Expected to open AcodeX server.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [LG VELVET]
 - OS: [Android 13]
 - Termux [from f-droid]
 - Version ?
![Screenshots_2024-02-14-13-29-30](https://github.com/bajrangCoder/acode-plugin-acodex/assets/158981227/910940f7-079d-4095-a6c3-7423d8e017b5)

**Comment by bajrangCoder** [comment]
From where you have installed termux?

**Comment by 8376459** [comment]
f-droid

**Comment by 8376459** [comment]
RESOLVED! I reinstalled and evrtng is ok.

**Comment by Aleeeksanders** [comment]
I have the same problem, Do you reinstall from the same page?
