### ISSUE TITLE
startup error acodeX-server

### ISSUE THREAD

**Issue by jonoto2** [bajrangCoder/acode-plugin-acodex#57]
telephone- Samsung a71 
Version Android 13
when I try to start the server I get an error  
![Screenshot_20240229_051635_Termux](https://github.com/bajrangCoder/acode-plugin-acodex/assets/78200473/581ca0d4-4574-4c7f-a51a-f492d0b1182c)

**Comment by bajrangCoder** [comment]
https://github.com/bajrangCoder/acode-plugin-acodex/issues/56#issuecomment-1972524171
