### ISSUE TITLE
cant save the theme change

### ISSUE THREAD

**Issue by Ponion** [bajrangCoder/acode-plugin-acodex#58]
everytime I closed the acode app the theme i setup was been initialized

the plugin version is 3.1.3

**Comment by bajrangCoder** [comment]
Do you mean that your custom theme is not saved?

**Comment by Ponion** [comment]
> Do you mean that your custom theme is not saved?

![IMG_20240319_175427](https://github.com/bajrangCoder/acode-plugin-acodex/assets/37197889/291c58ba-bae9-4fab-bea1-485c3e2bf68d)
i mark it on the screenshoot

**Comment by bajrangCoder** [comment]
This is weird because this saving etc are managed by Acode not by Plugins , please tell me other app settings are saved and remains same after restarting? Same as AcodeX plugin settings.

**Comment by Ponion** [comment]
no, just AcodeX plugin.it doesnt happen on Acode itself.I have tried for many times.I'd like to know does this only happen on my device.

**Comment by bajrangCoder** [comment]
> no, just AcodeX plugin.it doesnt happen on Acode itself.I have tried for many times.I'd like to know does this only happen on my device.

Maybe yes because no one had reported it.
Btw what's your Acode version?
And try to check settings.json(from Settings > Edit settings.json) file at `bajrangcoder.acodex` after modifying AcodeX plugin settings , is it updated with your latest changes or not?

**Comment by Ponion** [comment]
> > no, just AcodeX plugin.it doesnt happen on Acode itself.I have tried for many times.I'd like to know does this only happen on my device.
> 
> Maybe yes because no one had reported it. Btw what's your Acode version? And try to check settings.json(from Settings > Edit settings.json) file at `bajrangcoder.acodex` after modifying AcodeX plugin settings , is it updated with your latest changes or not?

ACODE:v1.8.7 device:oppo opd2201
and the setting.json remains same problem.It updated after i modified the setting but return to default after restarting acode.
Anyway,l'll close the issue several days later if no one meet the same problem,maybe it's really my device's problem

**Comment by bajrangCoder** [comment]
Please update your Acode to latest version because there was a bug in v1.8.7 related to settings, I guess that's the reason behind this

**Comment by Ponion** [comment]
> Please update your Acode to latest version because there was a bug in v1.8.7 related to settings, I guess that's the reason behind this

OK,l'll try

**Comment by Ponion** [comment]
however,it doesn't work.I update acode to v1.9.0 from f-droid,the problem still exists

**Comment by bajrangCoder** [comment]
> however,it doesn't work.I update acode to v1.9.0 from f-droid,the problem still exists

Then I guess any plugin is causing this issue.
Btw settings of other plugin works?
If you can then share a screen recording

**Comment by Misakamoe** [comment]
**Acode: 1.10.0 & AcodeX: 3.1.3**

After changing settings in AcodeX, upon reopening the application, the settings are reverted back. I've checked `settings.json` and noticed changes, but upon reopening the app, `settings.json` is restored to its previous state.

I have also installed other plugins like Prettier, and the modified settings are saved correctly.

**Comment by tharindu899** [comment]
can't save setting app after restart again default setting again,please fix that problem

**Comment by bajrangCoder** [comment]
@Misakamoe and @tharindu899, I am unable to reproduce the issue on my device. Could you please guide me on how to reproduce it? Alternatively, if you can identify the root cause, contributions are welcomed. Additionally, feel free to share your findings. If possible, could you also share the `setting.json` file of the `acodex` section? Furthermore, checking the logs would be beneficial in pinpointing the cause of the issue.

**Comment by tharindu899** [comment]
![Screenshot_20240328_211210](https://github.com/bajrangCoder/acode-plugin-acodex/assets/116081100/080be209-224c-4df7-9786-98e255d633f0)
![Screenshot_20240328_211249](https://github.com/bajrangCoder/acode-plugin-acodex/assets/116081100/9714df6c-c5db-4b52-bd28-299222399aed)
change setting and after restart like this

**Comment by tharindu899** [comment]
[after restart settings .json](https://github.com/bajrangCoder/acode-plugin-acodex/files/14792288/after.restart.settings.json)
[settings.json](https://github.com/bajrangCoder/acode-plugin-acodex/files/14792289/settings.json)

**Comment by bajrangCoder** [comment]
> [after restart settings .json](https://github.com/bajrangCoder/acode-plugin-acodex/files/14792288/after.restart.settings.json) [settings.json](https://github.com/bajrangCoder/acode-plugin-acodex/files/14792289/settings.json)

once check settings.json after changing acodex settings from its before restarting

> btw let me test it on some other devices because on my main device , I am not able to get this issue

**Comment by tharindu899** [comment]
acodex 3.0.1 is working bro.
