### ISSUE TITLE
Acodex:Error {isTrusted:true}

### ISSUE THREAD

**Issue by KJoo** [bajrangCoder/acode-plugin-acodex#60]
![Screenshot_20240330_150721_Acode](https://github.com/bajrangCoder/acode-plugin-acodex/assets/18454366/94ec3677-d267-48fe-9545-c03d63e8883f)
**Describe the bug**
Just says Acodex Error: {isTrusted: true} and I can't run any code or open terminal through Acode
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung S22+]
 - OS: [e.g. Android 14]
 - Termux [play store]
 - Version [e.g. Termux 0.118.0]

**Additional context**

**Comment by KJoo** [comment]
Forgot to mention that it just happens when opening the app for the first time. It'll just show the message

**Comment by bajrangCoder** [comment]
It's now no more , check this out
