### ISSUE TITLE
Two suggestions about terminals

### ISSUE THREAD

**Issue by LsxMm** [bajrangCoder/acode-plugin-acodex#62]
- [x] Can the terminal add replication function
- [x] Can the terminal add a button to clear the terminal's output

**Comment by bajrangCoder** [comment]
Thanks for your suggestion!

For your second suggestion I will add a shortcut to do that for eg: <kbd>Ctrl+I</kbd>

And can you explain bit more about your first suggestion

**Comment by LsxMm** [comment]
> 感谢您的建议！
> 
> 对于您的第二个建议，我将添加一个快捷方式来执行此操作，例如：Ctrl+I
> 
> 你能多解释一下你的第一个建议吗

The first suggestion is to long press the terminal without a pop-up copy option

**Comment by LsxMm** [comment]
https://github.com/bajrangCoder/acode-plugin-acodex/assets/86006776/f83c4af8-9238-40c5-a095-beee396be8f2

**Comment by bajrangCoder** [comment]
> > 感谢您的建议！
> > 对于您的第二个建议，我将添加一个快捷方式来执行此操作，例如：Ctrl+I
> > 你能多解释一下你的第一个建议吗
> 
> The first suggestion is to long press the terminal without a pop-up copy option

Currently there is no any full fledged touch screen support is available for touch device on terminal parser library used by Acodex but I am researching about alternatives , for just use double tap on words and press and hold to copy paste or use key shortcut

**Comment by bajrangCoder** [comment]
Your second feature request is added. Check https://github.com/bajrangCoder/acode-plugin-acodex/commit/2860097fdee1df61c7dd8b10515373aba1d1c4d9

**Comment by bajrangCoder** [comment]
Both features are now available check https://github.com/bajrangCoder/acode-plugin-acodex/pull/73
