### ISSUE TITLE
[Bug] Button is hidden behind tab after minimizing

### ISSUE THREAD

**Issue by jojorne** [bajrangCoder/acode-plugin-acodex#67]
Button is hidden behind tab after minimizing:

![Capture+_2024-08-15-13-03-59](https://github.com/user-attachments/assets/34c7dd60-7589-4555-9dc6-01a627bc7d0c)

Provide few details about your device(like Android version) , Plugin version.

latest version

**Comment by bajrangCoder** [comment]
Thanks for reporting ❤️

Soon it will be Fixed.

**Comment by jojorne** [comment]
Is it possible to place it next to these buttons?

![Capture+_2024-08-15-13-37-10](https://github.com/user-attachments/assets/688ea836-e127-4c9d-8432-b7a75bd3498f)

**Comment by bajrangCoder** [comment]
> Is it possible to place it next to these buttons?
> 
> ![Capture+_2024-08-15-13-37-10](https://private-user-images.githubusercontent.com/18329136/358305840-688ea836-e127-4c9d-8432-b7a75bd3498f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NDAzODYsIm5iZiI6MTcyMzc0MDA4NiwicGF0aCI6Ii8xODMyOTEzNi8zNTgzMDU4NDAtNjg4ZWE4MzYtZTEyNy00YzlkLTg0MzItYjdhNzViZDM0OThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE2NDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYzhlM2ExMGIzOGIxN2JiM2NhZjE3ZjMyNzg0OTRiMjI0M2U5YTAzNmRjOWNmYTRkMjYwYmNmMzEwNjY3YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xDA25_ju09LdFbLV7kdKdXEqn3XYhe2EmXTrigJfUBE)

It's possible but I wanted not to clutter the header bar that's why created custom button which is movable too

**Comment by jojorne** [comment]
It's just that I have a small screen so I even removed the Acode's float button.

![Capture+_2024-08-15-13-44-46](https://github.com/user-attachments/assets/e15755c4-9ce1-40eb-9634-2c38361d4e6d)

**Comment by bajrangCoder** [comment]
Ok then I will add an option to hide it and instead of button you will be able to use keyboard shortcuts

**Comment by bajrangCoder** [comment]
Check `v3.1.6`
