### ISSUE TITLE
Cannot find module "../build/Release/pty.node, how to solve?

### ISSUE THREAD

**Issue by CaRLos1227** [bajrangCoder/acode-plugin-acodex#7]
![Screenshot_20230401-000447_Termux](https://user-images.githubusercontent.com/96316594/229262836-e600d0f8-ab12-49f5-89f6-c88141c85ca4.jpg)

**Comment by bajrangCoder** [comment]
Share your Android version and from where you have downloaded termux?

**Comment by CaRLos1227** [comment]
> Share your Android version and from where you have downloaded termux?

I managed to use it, but only when I left ubuntu and went back to the default termux terminal, I downloaded the proot-distro and downloaded ubuntu in it and I use it in my daily life, but its plugin does not work when I run it while logged in

**Comment by bajrangCoder** [comment]
> > Share your Android version and from where you have downloaded termux?
> 
> I managed to use it, but only when I left ubuntu and went back to the default termux terminal, I downloaded the proot-distro and downloaded ubuntu in it and I use it in my daily life, but its plugin does not work when I run it while logged in, my version is 8.0.0

Oo , i haven't tested it in proot-distro, I thought it would work. If it will not work I will fix it. You can try it in Termux
Or just follow below method to install it in proot-distro

**Comment by bajrangCoder** [comment]
here is the method for installing acodeX-server in termux proot-distro:

1) sudo apt install unzip nodejs python make build-essential -y
2) rm -rf acodeX-server
3) mkdir acodeX-server
4) curl -L -o acodeXServer.zip https://github.com/bajrangCoder/acode-plugin-acodex/raw/main/server/acodeXServer.zip
5) unzip acodeXServer.zip -d ~/.acodeX-server
6) rm -rf acodeXServer.zip
7) cd ~/.acodeX-server
8) npm install
9) npm link .
10) navigate to bin folder in proot-distro and run
`chmod +x acodeX-server`
11) And restart your termux and then run `acodeX-server` in your termux proot-distro, then server will be started.
Hence Done :)

**Comment by CaRLos1227** [comment]
> here is the method for installing acodeX-server in termux proot-distro:
> 
> 1. sudo apt install unzip nodejs python make build-essential -y
> 2. rm -rf acodeX-server
> 3. mkdir acodeX-server
> 4. curl -L -o acodeXServer.zip https://github.com/bajrangCoder/acode-plugin-acodex/raw/main/server/acodeXServer.zip
> 5. unzip acodeXServer.zip -d ~/.acodeX-server
> 6. rm -rf acodeXServer.zip
> 7. cd ~/.acodeX-server
> 8. npm install
> 9. npm link .
> 10. navigate to bin folder in proot-distro and run
>     `chmod +x acodeX-server`
> 11. And restart your termux and then run `acodeX-server` in your termux proot-distro, then server will be started.
>     Hence Done :)

Oh thank you very much I will test it as soon as possible!
