### ISSUE TITLE
Typographical Error in Documentation

### ISSUE THREAD

**Issue by Raushang4** [bajrangCoder/acode-plugin-acodex#72]
There is a typographical error in the documentation where the word "weite" is incorrectly used instead of "write." This error may lead to confusion for users trying to understand the content.

Location of the Error:https://github.com/bajrangCoder/acode-plugin-acodex/blob/main/readme.md

https://github.com/bajrangCoder/acode-plugin-acodex/blob/97d38aa00f3be5a6d79bd09d2a1f9bc31e19b5d6/readme.md?plain=1#L36

**Comment by bajrangCoder** [comment]
Thanks for pointing out 👍, I will fix it.
